services:
  kafka:
    environment:
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://kafka:9092,BROKER://kafka:29092

  kafka-exporter:
    environment:
      KAFKA_SERVER: kafka:9092

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis://redis:6379