global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 로컬
#  - job_name: 'springboot'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['springboot:8080']

  #운영
  - job_name: 'springboot-green'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '43.200.2.244:8082' ]
  - job_name: 'springboot-blue'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '43.200.2.244:8081' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']