input {
    kafka {
        bootstrap_servers => "kafka:29092"
        topics => ["secure-agent-logs"]
        group_id => "secure-agent-logs-consumer"
        client_id => "logstash-secure-agent-logs"
        auto_offset_reset => "earliest"
        codec => "json"
    }
    kafka {
        bootstrap_servers => "kafka:29092"
        topics => ["secure-agent-events"]
        group_id => "secure-agent-events-consumer"
        client_id => "logstash-secure-agent-events"
        auto_offset_reset => "earliest"
        codec => "json"
    }
}

filter {
}

output {
    if [@metadata][kafka][topic] == "secure-agent-logs" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "secure-agent-logs"
        }
    }

    if [@metadata][kafka][topic] == "secure-agent-events" {
        elasticsearch {
          hosts => ["elasticsearch:9200"]
          index => "secure-agent-events"
        }
    }
}